export const copy={
 en:{brand:'Best Wishes',pageTitle:'Best Wishes — A quiet moment',description:'A quiet landscape for a wish, a thought, and a small moment of calm.',hero:'A quiet<br>moment.',intro:'Pause, reflect, and carry a kind thought with you.',eyebrow:'A LITTLE SPACE FOR YOU',enter:'Make a wish',home:'Back to the mountain',footer:'A little space to pause.',about:'About & privacy',aboutTitle:'About this little place',aboutCopy:['An imaginary landscape for reflection, with original preset writing. No predictions, accounts, or payments.','Your notes and photos stay in this browser and are not submitted to a server. Leaving an activity clears its on-page content. Downloads stay where you save them. Hosting may keep routine access logs.','Three.js powers the landscape. The keepsake illustration was created with AI; its words are set by this page.'],soundOn:'Sound on',soundOff:'Sound off',motionOn:'Motion on',motionOff:'Motion off',hint:'Drag to explore · Scroll to zoom',touchHint:'One finger to rotate · Pinch to zoom',zoomIn:'Zoom in',zoomOut:'Zoom out',rotate:'Auto rotate',reset:'Reset view',canvas:'Interactive 3D landscape. Arrow keys rotate; plus and minus zoom; R resets.',explore:'Explore',featured:'A MOMENT TO PAUSE',cat:'Take a little joy',gift:'A small gift for you',close:'Close',skip:'Skip to experience',journeys:'Experiences',loading:'The landscape is on its way…',fallback:'The 3D view is unavailable. You can still use every activity.',soundError:'Sound is unavailable on this device.',
 names:{shrine:'Make a wish',character:'One word',birthday:'Your season',palm:'In your hands',tree:'A quiet note'},
 subtitles:{shrine:'A moment for your wishes.',character:'Start with a word.',birthday:'A season to remember.',palm:'Your effort counts.',tree:'How are you today?'},
 descriptions:{shrine:'Write a wish, or simply keep it in mind.',character:'A word can be a small place to begin.',birthday:'Choose a date for a seasonal thought.',palm:'Remember one small thing your hands made possible.',tree:'A few words, just for yourself.'},
 wish:'Your wish (optional)',wishPlaceholder:'A little more care, a little more time.',quantity:'Incense sticks',begin:'Begin a quiet moment',incenseNote:'Virtual incense, just for the atmosphere.',again:'Start again',keep:'Keep a little thought',timeLeft:'seconds to pause',complete:'Stay as long as you like.',captions:['Let the moment slow down.','Breathe naturally, if comfortable.','You do not need every answer now.','A kind thought, a small next step.','Carry a little calm into your day.'],
 word:'Your word',wordPlaceholder:'Calm, hope, courage…',topic:'On your mind',topics:['Everyday life','Work','Relationships','Learning','Self-care'],reflect:'Find a reflection',wordError:'Enter one word, or one Chinese character.',chips:['安 · Calm','明 · Clarity','光 · Hope','爱 · Care'],date:'A date to remember',dateAction:'Explore this date',dateError:'Choose a valid date.',seasonNote:'A seasonal image based on the month.',photo:'Add a hand photo (optional)',photoHint:'JPG, PNG or WebP · Up to 8 MB · Stays on this device',photoError:'Choose a JPG, PNG or WebP image under 8 MB.',photoDecode:'This image could not be opened. Try another.',removePhoto:'Remove photo',effort:'One small thing you have done',effortPlaceholder:'Made a meal. Finished a page. Reached out.',effortAction:'Acknowledge your effort',effortResponse:'Small things count. Your hands have already made a difference today.',effortStep:'Tomorrow, choose one thing to make, finish, repair—or let yourself rest.',note:'What is on your mind?',notePlaceholder:'There is no perfect way to say it.',noteAction:'Read a gentle response',noteError:'Write a few words first.',noteDisclosure:'A preset response, chosen in your browser. No one is reading along. This space cannot offer emergency help.',responseTitle:'A little room for you',response:'You do not have to untangle everything today. What you feel deserves a little space.',responseStep:'Choose one manageable next step, or share a little of this with someone you trust.',workResponse:'You are more than what you get done. A difficult day does not erase your effort.',relationshipResponse:'It is okay to want care and understanding. Your needs deserve to be expressed with respect.',griefResponse:'Missing someone can take many shapes. There is no need to make it tidy or move at anyone else’s pace.',urgentTitle:'Your safety comes first.',urgent:'If you may hurt yourself or someone else now, contact local emergency services or go to the nearest emergency department. Ask someone you trust to stay with you and move away from things that could be used to cause harm. This page cannot provide live crisis support.',
 giftEyebrow:'SOMETHING TO KEEP',giftTitle:'A small wish for you',another:'Another',save:'Save image',giftError:'The image is unavailable. Please try again.',saved:'Your image is ready to save.',giftAlt:'Decorative keepsake',signature:'Best Wishes',giftFooter:'A kind thought. A small beginning.',
 reflection:'What does this word invite you to notice today?',steps:['Leave a little room for what makes an ordinary day kinder.','Choose one useful thing you can finish without rushing.','Make space for an honest, respectful conversation.','Try a small practice. Progress can be quiet.','Rest is something you can choose, too.'],seasons:['A fresh beginning','Room to grow','A softer pace','A quiet foundation'],seasonTexts:['Beginnings do not need to be dramatic. A small first step is enough.','Give a good idea a little time and attention. Growth has its own pace.','Notice what is ready to keep, and what you can gently set down.','There is value in quiet preparation. Rest can make room for what comes next.']},
 zh:{brand:'美好祝愿',pageTitle:'美好祝愿 — 留一点安静',description:'在山水之间，写下一份心愿，留一刻安静。',hero:'留一点<br>安静。',intro:'停一停，想一想，带上一句温柔的话。',eyebrow:'给自己的一点空间',enter:'写下心愿',home:'返回山间',footer:'留一点时间，停一停。',about:'关于与隐私',aboutTitle:'关于这片小天地',aboutCopy:['一处虚构的山水随想空间，使用原创预设文字。不预测未来，无需账号或付费。','心事和照片只在当前浏览器中处理，不提交到服务器。离开体验会清空页面内容；主动下载的文件由你保存。托管服务可能保留常规访问日志。','山景由 Three.js 绘制。挂件底图由 AI 创作，祝愿文字由页面排版生成。'],soundOn:'流水声 开',soundOff:'流水声 关',motionOn:'动态 开',motionOff:'动态 关',hint:'拖动旋转 · 滚轮缩放',touchHint:'单指旋转 · 双指缩放',zoomIn:'放大',zoomOut:'缩小',rotate:'自动环绕',reset:'重置视角',canvas:'可旋转的三维山景；方向键旋转，加减号缩放，R 重置。',explore:'山中一境',featured:'留一刻安静',cat:'带走一点欢喜',gift:'送你一份小礼物',close:'关闭',skip:'跳到体验内容',journeys:'山间体验',loading:'山景正在展开……',fallback:'暂时无法展示三维画面，仍可使用所有文字体验。',soundError:'当前设备暂时无法开启环境音。',
 names:{shrine:'写下心愿',character:'一字随想',birthday:'你的时节',palm:'亲手做到',tree:'留句心事'},
 subtitles:{shrine:'给心愿一点时间。',character:'从一个字开始。',birthday:'记住一个时节。',palm:'你的努力，值得看见。',tree:'今天过得怎么样？'},
 descriptions:{shrine:'写下来，也可以默念。',character:'从自己的联想，慢慢开始。',birthday:'选一个日期，留一句季节寄语。',palm:'想一件这双手完成的小事。',tree:'用自己的话，说给自己听。'},
 wish:'心愿（可选）',wishPlaceholder:'多一点关怀，多一点从容。',quantity:'香的数量',begin:'开始安静片刻',incenseNote:'一缕虚拟香烟，一段安静时光。',again:'再来一次',keep:'收下一句祝愿',timeLeft:'秒安静时光',complete:'愿意的话，可以再停留一会儿。',captions:['让这一刻慢下来。','如果舒适，就自然地呼吸。','不必现在就拥有所有答案。','一句温柔的话，一件小小的事。','带着一点安静，回到日常。'],
 word:'一个字或词',wordPlaceholder:'安、光、勇气……',topic:'想关注什么',topics:['日常','工作','关系','学习','照顾自己'],reflect:'看看这一字',wordError:'请输入一个词，或一至四个汉字。',chips:['安 · 安宁','明 · 清晰','光 · 希望','爱 · 关怀'],date:'想记住的日期',dateAction:'看看这个时节',dateError:'请选择有效日期。',seasonNote:'按月份选取的季节意象。',photo:'添加手部照片（可选）',photoHint:'JPG、PNG 或 WebP · 最大 8 MB · 仅留在本机',photoError:'请选择小于 8 MB 的 JPG、PNG 或 WebP 图片。',photoDecode:'无法打开这张图片，请试试另一张。',removePhoto:'移除照片',effort:'最近亲手做成的一件小事',effortPlaceholder:'做了一餐饭。读完了一页书。主动问候。',effortAction:'记下这份努力',effortResponse:'小事也值得被看见。这双手，已经为今天带来了一点不同。',effortStep:'给明天留一件小事：动手做、修一修、完成一步，或好好休息。',note:'此刻的心事',notePlaceholder:'不需要完美地表达。',noteAction:'读一句温柔回应',noteError:'先写下几句话吧。',noteDisclosure:'在浏览器中选取预设回应，没有真人在线阅读。这里无法提供紧急支持。',responseTitle:'给自己一点空间',response:'不必今天就解开所有的结。此刻的感受，值得被温柔地安放。',responseStep:'选一个力所能及的小步骤，或向信任的人说一说。',workResponse:'你不只是一张待办清单。艰难的一天，并不会抹去你已经付出的努力。',relationshipResponse:'希望得到关怀和理解，是可以的。你的需要，值得被尊重地表达。',griefResponse:'想念一个人，可以有很多种样子。不必整理得井井有条，也不必赶着跟上别人的节奏。',urgentTitle:'先让自己安全一些。',urgent:'如果你现在可能伤害自己或他人，请联系当地急救或前往最近的急诊。请信任的人陪在身边，远离可能造成伤害的物品。这里无法提供实时危机支持。',
 giftEyebrow:'留下一点美好',giftTitle:'送你一份小祝愿',another:'换一份',save:'保存图片',giftError:'暂时无法生成图片，请再试一次。',saved:'图片已准备好保存。',giftAlt:'装饰祝愿挂件',signature:'美好祝愿',giftFooter:'心有所安 · 行有所向',
 reflection:'这个字，让你留意到今天的什么？',steps:['给让日常变温柔的小事，留一点空间。','选一件有用的小事，不慌不忙地完成。','给一次真诚、尊重的交流，留一点时间。','一点点练习，也会慢慢带来进步。','休息，也可以是一种主动的选择。'],seasons:['新的开始','慢慢生长','放轻脚步','安静蓄力'],seasonTexts:['开始不必轰轰烈烈。迈出一小步，就很好。','给一个好想法，一点时间和照料。生长有自己的节奏。','看看哪些值得留下，哪些可以轻轻放下。','安静的准备，也有价值。休息会为下一步留出空间。']}
};
export const giftWords=[['Peace','平安'],['Progress','进展'],['Care','照料'],['Possibility','可能'],['Ease','从容'],['Light','有光'],['Joy','喜乐'],['Calm','安宁'],['Hope','期许'],['Fullness','丰盈'],['Acceptance','接纳'],['Gratitude','珍惜'],['Direction','方向'],['Connection','相遇'],['Together','相伴'],['Freedom','自在'],['Growth','生长'],['Practice','练习'],['Comfort','安好'],['Warmth','温暖'],['Support','支持'],['Courage','勇气'],['Delight','欢喜'],['Contentment','知足']];
export function validWord(value){return /^[\p{L}\p{M}]{1,24}$/u.test(value)&&(!/\p{Script=Han}/u.test(value)||Array.from(value).length<=4);}
export function seasonalIndex(value){const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);if(!match)return -1;const d=new Date(`${value}T12:00:00`);if(!Number.isFinite(d.getTime())||d.getFullYear()!==Number(match[1])||d.getMonth()+1!==Number(match[2])||d.getDate()!==Number(match[3]))return -1;return Math.floor((d.getMonth()+10)%12/3);}
export function noteKind(value){if(/kill myself|want to die|end my life|hurt myself|kill (him|her|them|someone)|suicid|自杀|不想活|想死|伤害自己|杀了|杀人|自残|结束生命/i.test(value))return 'urgent';if(/grief|died|passed away|miss (him|her|them)|去世|离世|想念|丧失/i.test(value))return 'grief';if(/work|job|exam|study|deadline|工作|考试|学习|上班|失业/i.test(value))return 'work';if(/friend|partner|love|relationship|朋友|伴侣|分手|感情|家人/i.test(value))return 'relationship';return 'general';}
