import React,{useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Play,Pause,RotateCcw,Maximize,Minimize,Video,Square,Download,Settings2,X,ArrowRight,ArrowUpRight,ChevronRight,SlidersHorizontal,Orbit,Network,LayoutGrid,Info,Leaf,Check,LoaderCircle,Layers,Activity,Languages,Move,MousePointer2,ZoomIn,ZoomOut,ArrowLeft,ArrowUp,ArrowDown} from 'lucide-react';
import Scene from './Scene.jsx';
import useStudio,{pct,fixed} from './useStudio.js';
import {METHOD_COLORS} from './Visuals.jsx';
import {Learning,Results} from './Pages.jsx';
import './styles.css';
import './studio.css';
import './refinements.css';
import {ExperimentControls,PatternSettings} from './Controls.jsx';
import LiveResources from './LiveResources.jsx';
import ServerInspector,{ServerHover} from './ServerInspector.jsx';
import OutcomeOverview from './OutcomeOverview.jsx';
import './exhibition.css';
import './interaction.css';
import './brand.css';
import './showcase.css';
function App(){const s=useStudio(),{t,labels,lang,config,history,model,result,states,playing,setPlaying,speed,setSpeed,busy,error,setError,notice,setNotice,section,setSection,setModal,selected,setSelected,methodView,rotate,setRotate,topology,setTopology,theme,resetKey,setResetKey,pulses,fullscreen,canvasRef,disabled,setLanguage,fullScreen,stopJob,run,replay,finish,arrived,done,activeConfig,current,pm,uplift,progressText}=s;const cameraControls=useRef(null),[cameraMode,setCameraMode]=useState('rotate'),[hovered,setHovered]=useState(null);
return <div className={'app theme-'+theme+(fullscreen?' presentation-mode':'')}>
<header className="topbar"><a className="brand-home" href="#" onClick={e=>{e.preventDefault();setSection('arena');}}><div className="brand-mark"><img className="carelab-symbol" src={import.meta.env.BASE_URL+'carelab-mark.svg'} alt="" aria-hidden="true"/></div><div className="brand"><b>CARELab <span>GREEN CLOUD</span></b><small>INTERACTIVE RESEARCH SHOWCASE</small></div></a><div className="top-slogan">{t('Less resource fragmentation.','更少资源碎片。')}{' '}{t('Towards a ','迈向')}<span>{t('greener','更绿色的')}</span>{t(' cloud.','云计算。')}</div><div className="header-actions"><span className="public-replay-pill"><i/>{t('Recorded simulation','仿真重播')}</span><a className="home-return" href="https://wilixx.github.io/">{t('Homepage','个人主页')}<ArrowUpRight size={14}/></a><button className="quiet language" onClick={setLanguage}><Languages size={16}/>{lang==='en'?'中文':'EN'}</button><button className="icon-button" title={fullscreen?t('Exit fullscreen','退出全屏'):t('Fullscreen','全屏显示')} aria-label={fullscreen?t('Exit fullscreen','退出全屏'):t('Fullscreen','全屏显示')} onClick={fullScreen}>{fullscreen?<Minimize size={18}/>:<Maximize size={18}/>}</button></div></header>
<div className="workspace"><aside className="sidebar"><button className="primary demo-button" onClick={()=>run('demo')} disabled={busy}><Play size={16} fill="currentColor"/>{t('Replay scenario','一键重播')}<span>100</span></button>
<nav><button className={section==='arena'?'active':''} onClick={()=>{setSection('arena');window.scrollTo({top:0,behavior:'smooth'});}}><Network size={17}/>{t('Allocation arena','放置展示')}</button><button className={section==='learning'?'active':''} onClick={()=>setSection('learning')}><Layers size={17}/>{t('History & combinations','历史与优质组合')}</button><button onClick={()=>{setSection('arena');setTimeout(()=>document.getElementById('compare-outcomes')?.scrollIntoView({behavior:'smooth'}),80);}}><Activity size={17}/>{t('Compare outcomes','对比结果')}</button></nav>
<ExperimentControls s={s}/><div className="sidebar-bottom"><span className="lab-name">MediaTek–SUTD Joint Lab</span><a className="paper-link" href="https://arxiv.org/abs/2609.21302" target="_blank" rel="noreferrer">Pattern-Aware Virtual Network Embedding Optimization for Cloud Data Centers<ArrowUpRight size={13}/></a><small>PIMRC 2026 · arXiv:2609.21302</small></div></aside>
<main className="main"><div className="status-stack">{error&&<div className="message error" role="alert"><Info size={18}/><span>{error}</span><button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
 {notice&&<div className="message" role="status"><Info size={17}/><span>{notice}</span><button className="icon-button" aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 {busy&&<div className="busy-strip" role="status"><LoaderCircle className="spin" size={18}/><span>{progressText}</span><small>{t('Recorded results','已记录的仿真结果')}</small><button className="quiet" onClick={stopJob}>{t('Cancel','取消')}</button></div>}
 </div>
{section==='arena'&&<><section className={'arena-screen'+(selected||s.modal==='servers'?' inspecting':'')}>
<div className="method-strip" style={{gridTemplateColumns:`repeat(${methodView.length},minmax(0,1fr))`}}>{methodView.map(k=>{const enabled=config.methods.includes(k);return <div className={'method-card '+(k==='pattern'?'selected ':'')+(!enabled?'muted-method':'')} style={{'--method-color':METHOD_COLORS[k]}} key={k}><div className="method-title"><label><input type="checkbox" checked={enabled} disabled={disabled||(enabled&&config.methods.length===1)} onChange={()=>s.toggleMethod(k)}/><span>{labels[k]}</span></label>{k==='pattern'?<PatternSettings s={s}/>:<button className="icon-button" title={t('Inspect servers','查看服务器')} aria-label={labels[k]+' '+t('servers','服务器')} disabled={!enabled} onClick={()=>{s.setServerMethod(k);setSelected({method:k,id:0});}}><ArrowUpRight size={13}/></button>}</div><div className="compact-metrics"><strong>{enabled?current(k).accepted:'—'}<em>VMs</em></strong><span><b>{pct(current(k).utilization)}</b> {t('util.','利用率')}</span><small>{current(k).rejected} {t('rejected','拒绝')}</small></div><div className="mini-track"><i style={{width:pct(current(k).utilization),background:METHOD_COLORS[k]}}/></div></div>})}</div>
<div className="arena"><div className="arena-stage"><div className="arena-top"><span>{activeConfig.servers} {t('servers / method','台服务器 / 方法')}</span><div><div className="camera-tools"><button className={'icon-button '+(cameraMode==='rotate'?'on':'')} aria-label={t('Rotate mode','旋转模式')} aria-pressed={cameraMode==='rotate'} title={t('Left drag to rotate','左键拖动旋转')} onClick={()=>setCameraMode('rotate')}><MousePointer2 size={15}/></button><button className={'icon-button '+(cameraMode==='pan'?'on':'')} aria-label={t('Pan mode','平移模式')} aria-pressed={cameraMode==='pan'} title={t('Left drag to pan','左键拖动平移')} onClick={()=>setCameraMode('pan')}><Move size={15}/></button><button className="icon-button" aria-label={t('Zoom in','放大视图')} title={t('Zoom in','放大视图')} onClick={()=>cameraControls.current?.zoom(.8)}><ZoomIn size={16}/></button><button className="icon-button" aria-label={t('Zoom out','缩小视图')} title={t('Zoom out','缩小视图')} onClick={()=>cameraControls.current?.zoom(1.25)}><ZoomOut size={16}/></button><button className="icon-button pan-arrow" aria-label={t('Pan left','向左平移')} title={t('Pan left','向左平移')} onClick={()=>cameraControls.current?.pan(-1,0)}><ArrowLeft size={13}/></button><button className="icon-button pan-arrow" aria-label={t('Pan up','向上平移')} title={t('Pan up','向上平移')} onClick={()=>cameraControls.current?.pan(0,1)}><ArrowUp size={13}/></button><button className="icon-button pan-arrow" aria-label={t('Pan down','向下平移')} title={t('Pan down','向下平移')} onClick={()=>cameraControls.current?.pan(0,-1)}><ArrowDown size={13}/></button><button className="icon-button pan-arrow" aria-label={t('Pan right','向右平移')} title={t('Pan right','向右平移')} onClick={()=>cameraControls.current?.pan(1,0)}><ArrowRight size={13}/></button></div><button title={t('Auto rotate','自动旋转')} aria-label={t('Auto rotate','自动旋转')} className={'icon-button '+(rotate?'on':'')} onClick={()=>setRotate(v=>!v)}><Orbit size={17}/></button><button title={t('Toggle network fabric','显示或隐藏网络')} aria-label={t('Toggle network fabric','显示或隐藏网络')} className={'icon-button '+(topology?'on':'')} onClick={()=>setTopology(v=>!v)}><Network size={17}/></button><button className="icon-button" title={t('Reset camera','重置视角')} aria-label={t('Reset camera','重置视角')} onClick={()=>setResetKey(k=>k+1)}><RotateCcw size={16}/></button><button className="quiet" onClick={()=>{s.setServerMethod(config.methods[0]);setSelected({method:config.methods[0],id:0});}}><LayoutGrid size={15}/>{t('Inspect servers','查看服务器')}</button></div></div>
<Scene count={activeConfig.servers} methods={methodView.filter(k=>config.methods.includes(k))} states={states} labels={labels} cameraMode={cameraMode} onControls={v=>cameraControls.current=v} onHover={setHovered} onSelect={(method,id,anchor)=>{setHovered(null);setSelected({method,id,anchor});}} selected={selected} pulses={pulses} rotate={rotate} topology={topology} theme={theme} resetKey={resetKey} onCanvas={c=>canvasRef.current=c}/>
{!result&&!busy&&<div className="arena-prompt"><span>{t('Spare capacity. Still rejecting workloads?','资源还有空闲，却放不下新业务？')}</span><button onClick={()=>run('simulate')}>{t('Play the scenario','播放场景')}<ArrowRight size={16}/></button></div>}
<ServerHover s={s} hovered={hovered}/><div className="scene-legend"><span><i style={{background:'#53ecc0'}}/>{t('Allocated','已分配')}</span><span><i style={{background:'#ffbd69'}}/>{t('Stranded capacity','碎片容量')}</span><small>{t('Drag: rotate · Wheel: zoom · Right drag: pan · Hover to inspect','拖动旋转 · 滚轮缩放 · 右键平移 · 悬停查看')}</small></div></div>
<ServerInspector s={s}/></div><div className="transport"><div className="play-controls"><button className="play-button" disabled={busy} aria-label={playing?t('Pause allocation','暂停放置'):t('Play allocation','开始放置')} onClick={()=>result?(done?replay():setPlaying(v=>!v)):run('simulate')}>{playing?<Pause size={18} fill="currentColor"/>:<Play size={18} fill="currentColor"/>}</button><button className="icon-button" disabled={!result} title={t('Replay same arrivals','重播相同业务')} aria-label={t('Replay same arrivals','重播相同业务')} onClick={replay}><RotateCcw size={17}/></button><label className="speed-select"><span>{t('Speed','速度')}</span><select aria-label={t('Playback speed','播放速度')} value={speed} onChange={e=>setSpeed(+e.target.value)}>{[.5,1,2,5,10,20,50,100].map(v=><option key={v} value={v}>{v}×</option>)}</select></label></div><div className="play-progress"><div><b>{busy?t('Loading…','载入中…'):done?t('Complete','已完成'):playing?t('Replaying placements','放置重播中'):result?t('Paused','已暂停'):t('Ready to explore','准备就绪')}</b><span>{arrived} / {result?.arrivals.length||config.arrivalCount} VMs</span></div><div className="bar-track"><i style={{width:result?arrived/result.arrivals.length*100+'%':'0%'}}/></div></div><button className="quiet" disabled={!result||done} onClick={finish}>{t('Show final','查看最终结果')}<ChevronRight size={16}/></button></div>
 <LiveResources s={s}/>
</section><OutcomeOverview s={s}/></>}
{section==='learning'&&<Learning s={s}/>}
<footer className="main-footer"><span>CARELab · MediaTek–SUTD Joint Lab</span><span>{t('Learn patterns from past. Build simple yet effective rules.','从历史中学习模式，形成简单有效的规则。')}</span></footer>
</main></div></div>;
}createRoot(document.getElementById('root')).render(<App/>);
