import React,{useState,useEffect} from 'react';
import {Layers,ArrowRight,ArrowUpRight,ChevronLeft,ChevronRight,Upload,Check,Info,Activity,Download,Leaf,Server,ExternalLink,ShieldCheck} from 'lucide-react';
import {METHOD_IDS} from './engine.js';
import {pct,fixed,download} from './useStudio.js';
import {COLORS,METHOD_COLORS,Radar,RuleCard,LineChart} from './Visuals.jsx';
import LearningDetails from './LearningDetails.jsx';
export function Learning({s}){const{t,lang,config,history,model,disabled,setModal,makeHistory,run,historyPage,setHistoryPage,historySource}=s;const[inspection,setInspection]=useState({kind:'vm',index:0});useEffect(()=>{setInspection(previous=>{const counts={vm:history.length,pattern:model?.patterns.length||0,rule:model?.rules.length||0};const kind=counts[previous.kind]?previous.kind:counts.vm?'vm':counts.pattern?'pattern':counts.rule?'rule':'vm';const index=Math.max(0,Math.min(previous.kind===kind?previous.index:0,counts[kind]-1));return previous.kind===kind&&previous.index===index?previous:{kind,index};});},[history,model]);const selectProfile=(kind,index)=>setInspection({kind,index});return <>
 <div className="page-heading learning-page-heading"><div><div className="eyebrow">{t('FROM EXPERIENCE TO SIMPLE RULES','从历史经验到简单规则')}</div><h1>{t('Learn the fit. Repeat the value.','学会如何搭配，持续释放价值。')}</h1><p>{t('Many resource dimensions. One reusable pattern vocabulary.','多维资源需求，转化为可复用的模式表征。')}</p></div><span className="recorded-caption">{t('Recorded history and combinations','已记录的历史与组合')}</span></div>
 <div className="learning-workspace"><div className="learning-main">
 <div className="flow-steps"><div><b>01</b><span>{t('Historical demand','历史需求')}<small>{history.length||'—'} VMs</small></span></div><ArrowRight/><div><b>02</b><span>{t('Workload patterns','业务模式')}<small>{model?.patterns.length||'—'} {t('patterns','类模式')}</small></span></div><ArrowRight/><div><b>03</b><span>{t('Reusable combinations','可复用组合')}<small>{model?.rules.length||'—'} {t('rules','条规则')}</small></span></div></div>
 <section className="panel"><div className="panel-title"><div><h3>{t('Workload history','历史业务画像')}</h3><p>{t('Select any VM to inspect its resource profile.','点击任意 VM 查看多维资源需求。')}</p></div></div>
 {!history.length?<div className="empty-panel"><Layers size={30}/><p>{t('Choose a recorded scenario in the sidebar.','请在侧栏选择一个已记录场景。')}</p></div>:<><div className="history-grid">{history.slice(historyPage*24,(historyPage+1)*24).map((vm,i)=><button className="history-vm" key={vm.id} aria-pressed={inspection.kind==='vm'&&inspection.index===historyPage*24+i} onClick={()=>selectProfile('vm',historyPage*24+i)}><div className="vm-icon" style={{width:26+vm.values.reduce((a,b)=>a+b,0)/vm.values.length*44,height:22+vm.values.reduce((a,b)=>a+b,0)/vm.values.length*28,background:COLORS[vm.values.indexOf(Math.max(...vm.values))%8]+'35',borderColor:COLORS[vm.values.indexOf(Math.max(...vm.values))%8]}}/><span>VM {vm.id+1}</span></button>)}</div><div className="pagination"><span>{t('Synthetic history · seed','合成历史 · 随机种子')}: {config.seed} · {history.length} VMs</span><div><button className="icon-button" disabled={!historyPage} aria-label="Previous history page" onClick={()=>setHistoryPage(p=>p-1)}><ChevronLeft size={16}/></button><span>{historyPage+1} / {Math.ceil(history.length/24)}</span><button className="icon-button" disabled={(historyPage+1)*24>=history.length} aria-label="Next history page" onClick={()=>setHistoryPage(p=>p+1)}><ChevronRight size={16}/></button></div></div></>}</section>
 {model&&<><section className="panel"><div className="panel-title"><div><h3>{t('Different needs. Complementary strengths.','不同需求，互补优势。')}</h3><p>{t('Resource profiles observed in the recorded history.','记录历史中的典型资源需求画像。')}</p></div><span className="tag">{model.patterns.length} {t('patterns','类模式')}</span></div><div className="pattern-grid">{model.patterns.map((p,i)=><button className="pattern-card" key={i} aria-pressed={inspection.kind==='pattern'&&inspection.index===i} onClick={()=>selectProfile('pattern',i)}><div><b style={{color:COLORS[i%8]}}>P{i+1}</b><span>{pct(p.count/history.length)} {t('of history','历史占比')}</span></div><Radar dimensions={config.dimensions} values={p.rep} second={p.centroid} color={COLORS[i%8]} size={190}/></button>)}</div></section>
 <section className="panel"><div className="panel-title"><div><h3>{t('Better together','组合之后，价值更大')}</h3><p>{t('Every learned combination clears the utilization threshold in every resource.','每个学得的优质组合，在每种资源上都满足利用率阈值。')}</p></div><div className="number-badge"><strong>{model.rules.length}</strong><span>{t('usable combinations','种可用组合')}</span></div></div>{model.rules.length?<div className="rules-grid">{model.rules.map((rule,i)=><div className={'learning-rule-cell '+(inspection.kind==='rule'&&inspection.index===i?'active':'')} key={i} onClick={e=>{if(!e.target.closest('button'))selectProfile('rule',i);}}><RuleCard rule={rule} index={i} patterns={model.patterns} dimensions={config.dimensions} lang={lang} onPattern={h=>selectProfile('pattern',h)}/><button className="learning-rule-open" aria-pressed={inspection.kind==='rule'&&inspection.index===i} onClick={()=>selectProfile('rule',i)}>{t('Inspect combination','查看组合详情')}<ArrowRight size={13}/></button></div>)}</div>:<div className="empty-panel"><Info/><h3>{t('No qualifying combination','没有满足阈值的组合')}</h3><p>{t('A high threshold is not always feasible. Adjust the threshold or workload mix.','过高的阈值可能无法实现，请调整阈值或业务结构。')}</p></div>}<div className="learning-summary"><span><Check size={15}/>{t('Recorded combinations','记录中的组合')}</span><span>{pct(model.coverage)} {t('pattern coverage','模式覆盖率')}</span></div>{model.coverage<1&&<div className="message error">{t('Some profiles have no qualifying combination in this record.','本场景中，部分画像没有满足阈值的组合。')}</div>}<p className="showcase-scope">{t('These are observable results from a recorded simulation. The public showcase contains no training or placement engine. Scenario outcomes vary with the workload mix.','这些是已记录仿真的可观察结果。公开展示不包含训练或放置引擎；不同业务结构会得到不同结果。')}</p></section><div className="next-step"><span>{t('See how these combinations performed.','查看这些组合在记录中的表现。')}</span><button className="primary" disabled={disabled} onClick={()=>run('simulate')}>{t('Replay these arrivals','重播此场景业务')}<ArrowRight size={16}/></button></div></>}
 </div><LearningDetails selection={inspection} history={history} model={model} dimensions={config.dimensions} lang={lang} onSelect={setInspection}/></div>
 </>;}
export function Results({s}){const{t,lang,labels,result,busy,run,done,finish,current,pm,uplift,chartMetric,setChartMetric,cursor,setModal,exportResults,exportCSV}=s;return <>
 <div className="page-heading"><div><h1>{t('Compare outcomes','对比结果')}</h1><p>{t('Compare service capacity, resource waste and decision cost.','对比业务承载、资源浪费和决策开销。')}</p></div>{result&&<button className="outline" disabled={busy} onClick={exportResults}><Download size={16}/>{t('Download result summary','下载结果摘要')}</button>}</div>
 {!result?<div className="panel empty-panel"><Activity size={36}/><h3>{t('Let the experiment tell the story.','让实验结果说明价值。')}</h3><p>{t('Run a demonstration to see measured placement outcomes.','运行一次演示，即可查看真实仿真的放置结果。')}</p><button className="primary" disabled={busy} onClick={()=>run('demo')}>{t('Run one-click demo','一键演示')}</button></div>:<>
 {!done&&<div className="message"><Activity size={17}/>{t('Showing the current playback position.','当前显示播放进度对应的结果。')}<button className="text-link" onClick={finish}>{t('Show final results','显示最终结果')}<ArrowRight size={15}/></button></div>}
 <div className="value-cards"><div><Leaf size={23}/><span>{t('Additional service capacity','业务承载量变化')}</span><strong>{result.methods.pattern&&result.methods.bestfit?(uplift>=0?'+':'')+fixed(uplift,1):'—'}<em>%</em></strong><small>{t('Pattern Matching vs Best Fit · this scenario','模式匹配相较最佳适应 · 当前场景')}</small></div><div><Server size={23}/><span>{t('Fleet resource utilization','全数据中心平均资源利用率')}</span><strong>{result.methods.pattern?fixed(pm.utilization*100,1):'—'}<em>%</em></strong><small>{t('Pattern Matching · mean across resources','模式匹配 · 各维度利用率平均值')}</small></div><div><Layers size={23}/><span>{t('Stranded free capacity','无法承载历史模式的空闲容量')}</span><strong>{result.methods.pattern?fixed(pm.stranded*100,1):'—'}<em>%</em></strong><small>{t('On active hosts unable to fit a representative','活跃服务器上放不下历史模式的剩余资源')}</small></div></div>
 <section className="panel"><div className="panel-title"><div><h3>{t('Every arrival. Every decision.','每次业务到达，每次放置决策。')}</h3><p>{t('Horizontal axis: incoming VMs. All methods share the same arrival sequence.','横轴为到达 VM 数量，所有方法使用相同序列。')}</p></div><select aria-label={t('Chart metric','图表指标')} value={chartMetric} onChange={e=>setChartMetric(e.target.value)}><option value="accepted">{t('VMs accepted','接纳 VM 数量')}</option><option value="utilization">{t('Fleet utilization','资源利用率')}</option><option value="stranded">{t('Stranded capacity','碎片容量')}</option></select></div><LineChart result={result} cursor={cursor} metric={chartMetric} lang={lang}/><div className="chart-legend">{(result.config.methods||Object.keys(result.methods)).map(k=><span key={k}><i style={{background:METHOD_COLORS[k]}}/>{labels[k]}</span>)}</div></section>
 <section className="panel"><div className="panel-title"><h3>{t('Same infrastructure. Full comparison.','相同基础设施，全面对比。')}</h3><button className="quiet" disabled={!done} onClick={exportCSV}><Download size={15}/>CSV</button></div><div className="table-scroll"><table><thead><tr><th>{t('Strategy','放置策略')}</th><th>{t('Accepted / rejected','接纳 / 拒绝')}</th><th>{t('Utilization','利用率')}</th><th>{t('Stranded','碎片容量')}</th><th>{t('Active hosts','活跃服务器')}</th><th>{t('Mean / p95 decision','平均 / p95 决策时间')}</th></tr></thead><tbody>{(result.config.methods||Object.keys(result.methods)).map(k=><tr key={k} className={k==='pattern'?'highlight-row':''} onClick={()=>{s.setServerMethod(k);s.setSelected({method:k,id:0});window.scrollTo({top:0,behavior:'smooth'});}}><td><i style={{background:METHOD_COLORS[k]}}/>{labels[k]}</td><td><b>{current(k).accepted}</b><span className="muted"> / {current(k).rejected}</span></td><td>{pct(current(k).utilization)}</td><td>{pct(current(k).stranded)}</td><td>{current(k).active}</td><td>{done?`${fixed(result.methods[k].metrics.meanDecisionMs,3)} / ${fixed(result.methods[k].metrics.p95DecisionMs,3)} ms`:'—'}</td></tr>)}</tbody></table></div><p className="fine-print">{t('Timing was recorded during offline simulation on the developer machine. It is not measured in your browser and is not a production SLA.','计时来自开发设备的离线仿真，并非您当前浏览器的实测结果，也不代表生产环境 SLA。')}</p></section>
 <details className="result-scope"><summary>{t('Model & baseline notes','模型与基线说明')}</summary><p>{t('Kubernetes-inspired approximates CPU/Memory LeastAllocated + BalancedAllocation scoring; it is not a complete Kubernetes scheduler. The fabric is a connected leaf–spine illustration, without network contention. Stranded capacity is idle capacity on active servers that cannot fit any historical representative. GPU capacity represents divisible slices.','Kubernetes 启发式近似 CPU / Memory 的 LeastAllocated 与 BalancedAllocation 评分，并非完整 Kubernetes 调度器。叶脊网络为全连通示意，不模拟链路争用。碎片指标统计活跃服务器上放不下任何历史代表性需求的空闲容量；GPU 按可分割切片处理。')}</p></details><section className="business-panel"><div className="business-icon"><Leaf size={36}/></div><div><div className="eyebrow">{t('TOWARDS A GREENER CLOUD','迈向更绿色的云')}</div><h2>{t('Serve more with what you already have.','用现有资源，服务更多业务。')}</h2><p>{t('Higher useful utilization can reduce hardware needs for a given workload. A pilot can validate this with your traces, operating constraints and measured server power.','提高有效利用率，有望降低承载相同业务所需的硬件规模。可结合您的真实业务数据、运维约束和实测功耗开展试点。')}</p><a className="text-link" href="https://wilixx.github.io/">{t('Explore a research collaboration','联系开展研究合作')}<ArrowUpRight size={15}/></a></div></section>
 </>}</>;}
