import {useState,useRef,useEffect,useMemo} from 'react';
import {DEFAULT_CONFIG,METHOD_IDS,emptyState,applyEvents,validateReplay} from './engine.js';
export const LABELS={en:{pattern:'Pattern Matching',random:'Random',k8s:'Kubernetes-inspired',bestfit:'Best Fit'},zh:{pattern:'模式匹配',random:'随机放置',k8s:'Kubernetes 启发式',bestfit:'最佳适应'}};
export const pct=value=>(value*100).toFixed(1)+'%',fixed=(value,n=2)=>Number(value||0).toFixed(n);
export function download(contents,filename,type='application/json'){const url=URL.createObjectURL(new Blob([contents],{type}));const link=document.createElement('a');link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function initialLanguage(){try{return localStorage.getItem('carelab-language')||'en';}catch{return'en';}}
export default function useStudio(){
 const [lang,setLang]=useState(initialLanguage),[config,setConfig]=useState(DEFAULT_CONFIG),[data,setData]=useState(null),[scenarios,setScenarios]=useState([]),[scenarioId,setScenarioId]=useState('complementary'),[states,setStates]=useState({}),[cursor,setCursor]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(5),[busy,setBusy]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[section,setSection]=useState('arena'),[selected,setSelected]=useState(null),[modal,setModal]=useState(null),[historyPage,setHistoryPage]=useState(0),[rotate,setRotate]=useState(false),[topology,setTopology]=useState(true),[theme,setTheme]=useState('aurora'),[resetKey,setResetKey]=useState(0),[pulses,setPulses]=useState([]),[fullscreen,setFullscreen]=useState(false),[chartMetric,setChartMetric]=useState('accepted'),[serverMethod,setServerMethod]=useState('pattern');
 const canvasRef=useRef(null),cursorRef=useRef(0),playRef=useRef(null),controller=useRef(null),cache=useRef(new Map());
 const t=(en,zh)=>lang==='en'?en:zh,labels=LABELS[lang],history=data?.history||[],model=data?.model||null;
 const result=useMemo(()=>data?{...data.result,config:{...data.result.config,methods:config.methods},methods:Object.fromEntries(config.methods.map(key=>[key,data.result.methods[key]]))}:null,[data,config.methods]);
 const resetPlayback=record=>{setPlaying(false);setCursor(0);cursorRef.current=0;setStates(Object.fromEntries(METHOD_IDS.map(key=>[key,emptyState(record.config.servers,record.config.dimensions.length)])));setSelected(null);setPulses([]);};
 const loadScenario=async(id,autoplay=false)=>{
  if(!/^(complementary|mixed-size|cpu-shift)$/.test(id))return;
  controller.current?.abort();const pending=new AbortController();controller.current=pending;setPlaying(false);setBusy(true);setError('');
  try{let next=cache.current.get(id);if(!next){const response=await fetch(`${import.meta.env.BASE_URL}scenarios/${id}.json`,{signal:pending.signal});if(!response.ok)throw Error('The recorded scenario could not be loaded. Please retry.');next=validateReplay(await response.json());cache.current.set(id,next);}if(pending.signal.aborted)return;
   setData(next);setConfig({...next.config,methods:[...METHOD_IDS]});setScenarioId(id);setHistoryPage(0);resetPlayback(next);setPlaying(autoplay);
  }catch(problem){if(problem.name!=='AbortError')setError(problem.message);}finally{if(controller.current===pending){setBusy(false);controller.current=null;}}
 };
 useEffect(()=>{const manifest=new AbortController();fetch(`${import.meta.env.BASE_URL}scenarios/manifest.json`,{signal:manifest.signal}).then(response=>{if(!response.ok)throw Error('Scenario list unavailable.');return response.json();}).then(value=>setScenarios(value.scenarios)).catch(problem=>{if(problem.name!=='AbortError')setError(problem.message);});loadScenario('complementary');return()=>{manifest.abort();controller.current?.abort();};},[]);
 playRef.current={playing,speed,data};
 useEffect(()=>{let last=performance.now(),credit=0,frame;const tick=now=>{const current=playRef.current,elapsed=Math.min(.25,(now-last)/1000);last=now;if(current.playing&&current.data){credit+=elapsed*6*current.speed;const count=Math.floor(credit);if(count){credit-=count;const record=current.data.result,from=cursorRef.current,to=Math.min(record.arrivals.length,from+count);cursorRef.current=to;setCursor(to);setStates(previous=>Object.fromEntries(METHOD_IDS.map(key=>[key,applyEvents(previous[key]||emptyState(record.config.servers,4),record.methods[key].events.slice(from,to),current.data.model.patterns)])));setPulses(METHOD_IDS.flatMap(key=>record.methods[key].events.slice(Math.max(from,to-2),to).flatMap(event=>event.placements.map(p=>({method:key,server:p.server})))).slice(0,12));if(to>=record.arrivals.length){setPlaying(false);credit=0;}}}else credit=0;frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[]);
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});},[section]);
 useEffect(()=>{const changed=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',changed);return()=>document.removeEventListener('fullscreenchange',changed);},[]);
 useEffect(()=>{const escape=event=>{if(event.key==='Escape'){setSelected(null);setModal(null);if(!document.fullscreenElement)setFullscreen(false);}};document.addEventListener('keydown',escape);return()=>document.removeEventListener('keydown',escape);},[]);
 const setLanguage=()=>setLang(previous=>{const next=previous==='en'?'zh':'en';try{localStorage.setItem('carelab-language',next);}catch{}document.documentElement.lang=next==='en'?'en':'zh-CN';return next;});
 const fullScreen=async()=>{if(fullscreen){setFullscreen(false);if(document.fullscreenElement)await document.exitFullscreen().catch(()=>{});}else{setFullscreen(true);try{await document.documentElement.requestFullscreen?.();}catch{setNotice(t('Presentation view expanded.','已展开演示视图。'));}}};
 const replay=()=>{if(data){resetPlayback(data);setPlaying(true);}};
 const run=()=>{setSection('arena');data?replay():loadScenario(scenarioId,true);};
 const finish=()=>{if(!data)return;setPlaying(false);const count=data.result.arrivals.length;cursorRef.current=count;setCursor(count);setStates(Object.fromEntries(METHOD_IDS.map(key=>[key,{...data.result.methods[key].metrics,servers:data.result.methods[key].servers}])));setPulses([]);};
 const toggleMethod=key=>{setConfig(previous=>{const methods=previous.methods.includes(key)?previous.methods.filter(k=>k!==key):METHOD_IDS.filter(k=>k===key||previous.methods.includes(k));if(!methods.length)return previous;if(selected?.method===key)setSelected(null);return{...previous,methods};});};
 const current=key=>states[key]||emptyState(config.servers,config.dimensions.length),pm=current('pattern'),bf=current('bestfit'),uplift=bf.accepted?(pm.accepted/bf.accepted-1)*100:0;
 const exportResults=()=>{if(data)download(JSON.stringify({kind:'recorded-showcase-results',scenario:data.name,provenance:data.provenance,config:data.config,metrics:Object.fromEntries(METHOD_IDS.map(key=>[key,data.result.methods[key].metrics]))},null,2),'CARELab-'+scenarioId+'-summary.json');};
 const exportCSV=()=>{if(!data)return;const lines=['method,accepted_vms,rejected_vms,fleet_utilization,stranded_capacity,active_servers,recorded_mean_decision_ms'];for(const key of config.methods){const m=data.result.methods[key].metrics;lines.push([key,m.accepted,m.rejected,m.utilization,m.stranded,m.active,m.meanDecisionMs].join(','));}download(lines.join('\n'),'CARELab-'+scenarioId+'-comparison.csv','text/csv');};
 return{lang,config,history,model,result,states,cursor,playing,setPlaying,speed,setSpeed,busy,error,setError,notice,setNotice,section,setSection,selected,setSelected,modal,setModal,historyPage,setHistoryPage,historySource:'recorded',methodView:METHOD_IDS,rotate,setRotate,topology,setTopology,theme,setTheme,resetKey,setResetKey,pulses,fullscreen,chartMetric,setChartMetric,serverMethod,setServerMethod,canvasRef,t,labels,disabled:busy,setLanguage,fullScreen,run,replay,finish,arrived:cursor,done:!!data&&cursor===data.result.arrivals.length,activeConfig:config,current,pm,uplift,progressText:t('Loading recorded scenario…','正在载入仿真重播…'),stopJob:()=>{controller.current?.abort();setBusy(false);},toggleMethod,exportResults,exportCSV,scenarios,scenarioId,scenario:data,loadScenario};
}
