name: Jekyll site CI

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Build with the GitHub Pages Jekyll environment
        uses: actions/jekyll-build-pages@v1
        with:
          future: true
